pipeline {
    agent any

    parameters {
        choice(
            name: 'ENV',
            choices: ['prod', 'stage'],
            description: 'Target environment'
        )
        choice(
            name: 'SUITE',
            choices: ['smoke', 'regression'],
            description: 'Test suite to run'
        )
    }


    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify TTS Tooling') {
            steps {
                // Voice-query audio is now generated by edge-tts (Microsoft's free neural TTS) +
                // ffmpeg instead of OS-specific engines (SAPI/say/espeak), so both must be on PATH
                // for the test JVM to shell out to. Installs are no-ops once already present.
                // Verified via "python -m edge_tts" rather than the bare edge-tts.exe stub —
                // pip's auto-generated console-script wrappers are unsigned, and Windows Smart
                // App Control blocks them once it graduates out of evaluation mode; going
                // through python.exe instead avoids that (see EdgeTtsEngine.java).
                bat '''
                where edge-tts >nul 2>nul || pip install --quiet edge-tts
                where ffmpeg >nul 2>nul || winget install --id Gyan.FFmpeg -e --accept-source-agreements --accept-package-agreements
                python -m edge_tts --version
                ffmpeg -version
                '''
            }
        }

        stage('Run Tests') {
            steps {
                bat "mvn clean test -DtestGroups=${params.SUITE} -Denv=${params.ENV}"
            }
        }
    }

    post {
        always {
            // 1. Archive Extent report as a downloadable build artifact
            archiveArtifacts artifacts: 'target/extent-report/index.html', allowEmptyArchive: true

            // 2. Publish surefire XML for Jenkins test trend graph
            junit allowEmptyResults: true, testResults: '**/target/surefire-reports/*.xml'

            // 3. Publish Extent HTML report as a Jenkins build link
            // Requires: HTML Publisher Plugin
            publishHTML(target: [
                allowMissing         : true,
                alwaysLinkToLastBuild: true,
                keepAll              : true,
                reportDir            : 'target/extent-report',
                reportFiles          : 'index.html',
                reportName           : "Test Report — ${params.ENV} | ${params.SUITE}"
            ])

            // 4. Archive + publish the custom failure dashboard as a Jenkins build link
            archiveArtifacts artifacts: 'target/dashboard-report/index.html', allowEmptyArchive: true

            publishHTML(target: [
                allowMissing         : true,
                alwaysLinkToLastBuild: true,
                keepAll              : true,
                reportDir            : 'target/dashboard-report',
                reportFiles          : 'index.html',
                reportName           : "Dashboard — ${params.ENV} | ${params.SUITE}"
            ])

        }

        failure {
            echo "Tests FAILED on ${params.ENV} | suite=${params.SUITE}"
        }

        unstable {
            echo "Tests UNSTABLE (failures present) on ${params.ENV} | suite=${params.SUITE}"
        }

        success {
            echo "Tests PASSED on ${params.ENV} | suite=${params.SUITE}"
        }
    }
}
